### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by vijay03** [gk159yo/script_optfs#1]
See CrashMonkey repo for example (https://github.com/utsaslab/crashmonkey).

**Comment by yoloVoe** [comment]
Added some documentation.

**Comment by vijay03** [comment]
Great work! Can you add details about how safe the transformation is? Could a fsync() erroneously be converted into an osync() (and thus compromise program correctness?)

You should add an overview of how the tool works.

**Comment by yoloVoe** [comment]
Ok. I added both. Let me know if you need any more changes.

**Comment by vijay03** [comment]
This is great. I don't understand the if-conditional example for comprising correctness. You should add more detail there.

Also, can me name this tool something else? AutoOsync?

**Comment by yoloVoe** [comment]
Ok. Done. Replaced with another example.
And AutoOsync sounds pretty good.

**Comment by vijay03** [comment]
You should also release this under the Apache 2.0 license.

**Comment by yoloVoe** [comment]
Done.
